version: '3.8'

services:
  web:
    image: navidificador/navidificador:latest
    container_name: navidificador
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MASK_HUGGINGFACE_ENDPOINT: ${MASK_HUGGINGFACE_ENDPOINT}
      MASK_HUGGINGFACE_BEARER: ${MASK_HUGGINGFACE_BEARER}
    ports:
      - 127.0.0.1:8000:8000

