ARG BASE_IMAGE
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      gcc \
      python3-dev python-is-python3 python3-venv python3-distutils python3-wheel pipenv \
    && apt-get autoremove --purge -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/src/*


RUN python3 -m venv /venv

# We need pip updated in the venv so that cryptography can be installed properly
# https://github.com/python-poetry/poetry/issues/3329#issuecomment-724081350
# Also, pip should be upgraded in the same RUN command so that pip upgrade is not cached
# in a different layer than poetry install, for the same reason as above.
ARG DEVICE
ENV DEVICE=$DEVICE \
    TORCH_HOME=/venv/torch
COPY requirements-${DEVICE}.txt post-install.sh /tmp/
RUN echo "DEVICE=${DEVICE}"

ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

RUN mkdir /models && cd /tmp \
  && . /venv/bin/activate \
  && pip install -U pip wheel \
  && pip install -r "/tmp/requirements-${DEVICE}.txt" \
  && sh /tmp/post-install.sh
