version: '3.8'

services:
  web:
    image: navidificador/navidificador:latest
    container_name: navidificador
    env_file: .env
    ports:
      - 127.0.0.1:8000:8000

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1460
